src/Entity/User.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use App\Entity\Trait\RegistredAtTrait;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Scheb\TwoFactorBundle\Model\Email\TwoFactorInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, TwoFactorInterface
{
    
    use RegistredAtTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column(nullable: true)]
    private ?string $authCode;

    #[ORM\Column]
    private array $roles = ['ROLE_USER'];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $FirstName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $MiddleName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $LastName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Mobile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Vendor = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $LastLogin = null;

    #[ORM\Column(length: 1, nullable: true)]
    private ?string $intro = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Profile = null;

    #[ORM\OneToMany(mappedBy: 'UserId', targetEntity: Product::class)]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    private Collection $Products;

    #[ORM\OneToMany(mappedBy: 'Utilisateur', targetEntity: Order::class)]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    private Collection $orders;

    public function __construct()
    {
        $this->Products = new ArrayCollection();
        $this->orders = new ArrayCollection();
        $this->RegistredAt = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(?string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getMiddleName(): ?string
    {
        return $this->MiddleName;
    }

    public function setMiddleName(?string $MiddleName): self
    {
        $this->MiddleName = $MiddleName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(?string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getMobile(): ?string
    {
        return $this->Mobile;
    }

    public function setMobile(?string $Mobile): self
    {
        $this->Mobile = $Mobile;

        return $this;
    }

    public function getVendor(): ?string
    {
        return $this->Vendor;
    }

    public function setVendor(?string $Vendor): self
    {
        $this->Vendor = $Vendor;

        return $this;
    }

    public function getLastLogin(): ?\DateTimeImmutable
    {
        return $this->LastLogin;
    }

    public function setLastLogin(?\DateTimeImmutable $LastLogin): self
    {
        $this->LastLogin = $LastLogin;

        return $this;
    }

    public function getIntro(): ?string
    {
        return $this->intro;
    }

    public function setIntro(?string $intro): self
    {
        $this->intro = $intro;

        return $this;
    }

    public function getProfile(): ?string
    {
        return $this->Profile;
    }

    public function setProfile(?string $Profile): self
    {
        $this->Profile = $Profile;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->Products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->Products->contains($product)) {
            $this->Products->add($product);
            $product->setUserId($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->Products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getUserId() === $this) {
                $product->setUserId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setUtilisateur($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUtilisateur() === $this) {
                $order->setUtilisateur(null);
            }
        }

        return $this;
    }
    
    public function isEmailAuthEnabled(): bool
    {
        return true; // This can be a persisted field to switch email code authentication on/off
    }

    public function getEmailAuthRecipient(): string
    {
        return $this->email;
    }

    public function getEmailAuthCode(): string
    {
        if (null === $this->authCode) {
            throw new \LogicException('The email authentication code was not set');
        }

        return $this->authCode;
    }

    public function setEmailAuthCode(string $authCode): void
    {
        $this->authCode = $authCode;
    }
}

src/Controller/Profile/CheckoutController.php
<?php

namespace App\Controller\Profile;

use Stripe\Stripe;
use App\Entity\Cart;
use App\Entity\Order;
use App\Form\OrderType;
use App\Services\StripeServives;
use App\Repository\UserRepository;
use App\Repository\OrderRepository;
use App\Services\AddtocartServices;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CheckoutController extends AbstractController
{
    private AddtocartServices $AddtocartServices;
    private StripeServives $StripeServives;

    public function __construct(AddtocartServices $AddtocartServices, StripeServives $StripeServives)
    {
        $this->AddtocartServices = $AddtocartServices;
        $this->StripeServives = $StripeServives;
    }

    #[Route('/profile/checkout', name: 'profile_checkout')]
    #[isGranted('ROLE_USER')]
    public function index(Request $request, EntityManagerInterface $em, UserRepository $user): Response
    {
        // creation du Formulaire
        $Order = new Order();
        $form = $this->createForm(OrderType::class, $Order);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $Order->setUtilisateur($user->find($this->getUser()->getId()));
            $em->persist($Order);
            $em->flush();

            return $this->redirectToRoute('profile_paiement');
        }

        return $this->render('profile/checkout/index.html.twig', [
            'Order' => $form->createView(),
        ]);
    }

    #[Route('/profile/paiement', name: 'profile_paiement')]
    #[isGranted('ROLE_USER')]
    public function Paiement(Request $request): Response
    {
        // Je créer le btn submit dans le formulaire de paiement
        // pour avoir du code différent et d'autre possibilité je fais le formulaire dans le controller
        // et non dans le répertoir form
        // PS: A EVITE DE FAIRE COMME CELA
        $form = $this->createFormBuilder()
                        ->add('submit', SubmitType::class, [
                            'attr' => [
                                'class' => 'btn theme-btn-1 btn-effect-1 text-uppercase'
                            ]
                        ])->getForm();

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            // $success = $this->generateUrl('success_url', [], UrlGeneratorInterface::ABSOLUTE_URL);
            $cancel =  $this->generateUrl('cancel_url', [], UrlGeneratorInterface::ABSOLUTE_URL);
            $ValidStripe  = $this->StripeServives->PaiementStripe($cancel, $this->AddtocartServices->getFullCart());
            return $this->redirect($ValidStripe->url, 303);

        }

        return $this->render('profile/checkout/paiement.html.twig', [
            'items' => $this->AddtocartServices->getFullCart(),
            'total' => $this->AddtocartServices->getTotal(),
            'form' => $form->createView(),
        ]);
    }

    #[Route('/profile/success', name: 'success_url')]
    #[isGranted('ROLE_USER')]
    public function success_url(Request $request, OrderRepository $order, ManagerRegistry $em): Response
    {

        $Session_id_stripe = $request->query->get('session_id');
        $stripe = new \Stripe\StripeClient($_ENV['STRIPE_SK']);

        $session = $stripe->checkout->sessions->retrieve($Session_id_stripe);
        $customer = $stripe->customers->retrieve($session->customer);
        $id_stripe = $customer->id;

        $UpdateOrder = $order->findOneBy(
            ['Utilisateur' => $this->getUser()->getId()],
            ['id' => 'DESC']
        );

        if(!$UpdateOrder) {
            throw $this->createNotFoundException('L\'utilisateur n existe pas');
        }

        $UpdateOrder->setToken($id_stripe);
        $UpdateOrder->setStatus(1); // 1 = payé
        $UpdateOrder->setTax('0.2');
        $UpdateOrder->setTotal($this->AddtocartServices->getTotal());
        $UpdateOrder->setSubTotal($this->AddtocartServices->getTotal() / 1.2); // affiche le montant HT
        
        foreach($this->AddtocartServices->getFullCart() as $carts) {
            $cart = new Cart();
            $cart->setTitle($carts['produit']->getTitle());
            $cart->setPrice($carts['produit']->getPrice());
            $cart->setQuantity($carts['quantity']);
            $cart->setSKU($carts['produit']->getSKU());
            $cart->setDiscount($carts['produit']->getDiscount());
            $cart->setOrders($UpdateOrder);
            $em->getManager()->persist($cart);
        }

        try {
            $em->getManager()->flush();
        } catch (\Exception $e) {
            throw $e;
        }

         return $this->render('profile/checkout/paiement_success.html.twig', [
            'total' => $this->AddtocartServices->getTotal()
        ]);
    }

    #[Route('/profile/cancel', name: 'cancel_url')]
    #[isGranted('ROLE_USER')]
    public function cancel_url(): Response
    {
        return $this->render('profile/checkout/paiement_cancel.html.twig');
    }
}

src/Controller/Profile/DashboardController.php
<?php

namespace App\Controller\Profile;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class DashboardController extends AbstractController
{
    #[Route('/profile/dashboard', name: 'profile_dashboard')]
    #[isGranted('ROLE_USER')]
    public function index(): Response
    {
        return $this->render('profile/dashboard/index.html.twig', [
            'controller_name' => 'DashboardController',
        ]);
    }
}

src/Controller/Profile/OrderController.php
<?php

namespace App\Controller\Profile;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class OrderController extends AbstractController
{
    #[Route('/order', name: 'profile_order')]
    public function index(): Response
    {
        return $this->render('profile/order/index.html.twig', [
            'controller_name' => 'OrderController',
        ]);
    }
}

src/Controller/Profile/PdfController.php
<?php

namespace App\Controller\Profile;

use Knp\Snappy\Pdf;
use App\Entity\Order;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PdfController extends AbstractController
{
    #[Route('/profile/pdf/{id}', name: 'profile_pdf')]
    public function pdfAction(Pdf $knpSnappyPdf, $id, Order $order)
    {
        $html = $this->render('facture/facture.html.twig', [
            'Order'  => $order
        ]);

        return new PdfResponse(
            $knpSnappyPdf->getOutputFromHtml($html),
            'file.pdf'
        );
    }
}

src/Controller/Profile/ProfileOrderController.php
<?php

namespace App\Controller\Profile;

use App\Repository\OrderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProfileOrderController extends AbstractController
{
    public function ViewOrder(OrderRepository $order): Response
    {  
        return $this->render('profile/order/index.html.twig', [
            'history' => $order->findBy(['Utilisateur' => $this->getUser()]),
        ]);
    }
}

templates/profile/chekout/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ChekoutController!{% endblock %}

{% block body %}
    <!-- BREADCRUMB AREA START -->
    <div class="ltn__breadcrumb-area ltn__breadcrumb-area-4 ltn__breadcrumb-color-white---">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ltn__breadcrumb-inner text-center">
                        <h1 class="ltn__page-title">Checkout</h1>
                        <div class="ltn__breadcrumb-list">
                            <ul>
                                <li><a href="index.html">Home</a></li>
                                <li>Checkout</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- BREADCRUMB AREA END -->

    <!-- WISHLIST AREA START -->
    <div class="ltn__checkout-area mb-100">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ltn__checkout-inner">
                        <div class="ltn__checkout-single-content mt-50">
                            <h4 class="title-2">Billing Details</h4>
                            <div class="ltn__checkout-single-content-info">
                                {{ form_start(Order, {attr: {'novalidate': 'novalidate'}}) }}
                                    <h6>Personal Information</h6> 
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="input-item input-item-name ltn__custom-icon">
                                                {{ form_widget(Order.firstName) }}
                                                {{ form_errors(Order.firstName) }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="input-item input-item-name ltn__custom-icon">
                                                {{ form_widget(Order.lastName) }}
                                                {{ form_errors(Order.lastName) }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="input-item input-item-email ltn__custom-icon">
                                                {{ form_widget(Order.mobile) }}
                                                {{ form_errors(Order.mobile) }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="input-item input-item-phone ltn__custom-icon">
                                                {{ form_widget(Order.middleName) }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12">
                                            <h6>Address</h6>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="input-item">
                                                        {{ form_widget(Order.line1) }}
                                                        {{ form_errors(Order.line1) }}
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="input-item">
                                                        {{ form_widget(Order.line2) }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <h6>Town / City</h6>
                                            <div class="input-item">
                                                {{ form_widget(Order.city) }}
                                                {{ form_errors(Order.city) }}
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <h6>State </h6>
                                            <div class="input-item">
                                                {{ form_widget(Order.province) }}
                                                {{ form_errors(Order.province) }}
                                            </div>
                                        </div>
                                        <div class="col-lg-4 col-md-6">
                                            <h6>Country</h6>
                                            <div class="input-item">
                                                {{ form_widget(Order.country) }}
                                                {{ form_errors(Order.country) }}
                                            </div>
                                        </div>
                                    </div>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12">
                                        {{ form_widget(Order.Zip) }}
                                        {{ form_errors(Order.Zip) }}
                                    </div>
                                </div>
                                    <h6>Order Notes (optional)</h6>
                                    <div class="input-item input-item-textarea ltn__custom-icon">
                                        {{ form_widget(Order.content) }}
                                    </div>
                                    <button class="btn theme-btn-1 btn-effect-1 text-uppercase" type="submit">Paiement</button>
                                    {{ form_end(Order) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- WISHLIST AREA START -->

    <!-- BRAND LOGO AREA START -->
    <div class="ltn__brand-logo-area  ltn__brand-logo-1 section-bg-1 pt-35 pb-35 plr--5">
        <div class="container-fluid">
            <div class="row ltn__brand-logo-active">
                <div class="col-lg-12">
                    <div class="ltn__brand-logo-item">
                        <img src="img/brand-logo/1.png" alt="Brand Logo">
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="ltn__brand-logo-item">
                        <img src="img/brand-logo/2.png" alt="Brand Logo">
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="ltn__brand-logo-item">
                        <img src="img/brand-logo/3.png" alt="Brand Logo">
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="ltn__brand-logo-item">
                        <img src="img/brand-logo/4.png" alt="Brand Logo">
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="ltn__brand-logo-item">
                        <img src="img/brand-logo/5.png" alt="Brand Logo">
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="ltn__brand-logo-item">
                        <img src="img/brand-logo/1.png" alt="Brand Logo">
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="ltn__brand-logo-item">
                        <img src="img/brand-logo/2.png" alt="Brand Logo">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- BRAND LOGO AREA END -->
{% endblock %}